apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # Linux: echo -n 'your-secret-value' | base64
  # Windows: powershell "[convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes('your-secret-value'))"
  postgres-password: cG9zdGdyZXM=  # postgres
  secret-key: U0VDUkVU  # SECRET
  imagga-api-key: xxxxxxxxxxxxxxxxxxxxxxxxxx==
  imagga-api-secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=